### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by jakesherman** [openeemeter/eeweather#14]
I tried installing this package with Python 3.6.5 in a brand-new `conda` environment, and got a `ModuleNotFoundError` error. Here is the traceback:

```python
Python 3.6.5 |Anaconda, Inc.| (default, Apr 26 2018, 08:42:37)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import eeweather
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda3/envs/py3test/lib/python3.6/site-packages/eeweather/__init__.py", line 19, in <module>
    from .api import (
  File "/anaconda3/envs/py3test/lib/python3.6/site-packages/eeweather/api.py", line 3, in <module>
    from .connections import metadata_db_connection_proxy
  File "/anaconda3/envs/py3test/lib/python3.6/site-packages/eeweather/connections.py", line 5, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

Here's the code I used to get here:

```bash
conda create --name py3test python=3.6
source activate py3test
pip install eeweather
```

I'm wondering if this needs to be updated with `requests`?

```
# setup.py
REQUIRED = [
    'click',
    'pandas',
]
```

**Comment by philngo** [comment]
Agreed with your assessment - that is an oversight and we should add `requests` to the setup.py. Can you make a PR for that? I think we missed it because the dev environment has requests installed. As you dive deeper you will find some other dependencies that are not required initially, but will prompt for install (shapely, pyproj).

**Comment by jakesherman** [comment]
Sure thing!
